import type { Metadata } from "next";
import "../../globals.css";
import Sidebar from "./_components/Sidebar/sidebar";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
      <Sidebar />
      <div className="w-full px-6 sm:px-8">{children}</div>
    </div>
  );
}
