import type { Metadata } from "next";
import "@/app/styles/globals.css";
import Header from "@/components/Header/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
  sidebar,
}: {
  children: React.ReactNode;
  sidebar: React.ReactNode;
}) {
  return (
    <div className="flex">
      {sidebar}
      {children}
    </div>
  );
}
